### ISSUE TITLE
extra create buttons bring up modal, when finished or cancel return to original modal

### ISSUE THREAD

**Issue by mpanoratra** [mpanoratra/cs347_final_project#13]
Ex. creating an employee, need to add a new lab/div. should pop up a new modal, if finished or cancel return to the create employee modal

**Comment by dededecline** [comment]
Created buttons that successfully redirect, next I'll be ensuring that the newly created modal dialogues return to the page that spawned them and making the buttons on the employee page look more aesthetically pleasing

**Comment by dededecline** [comment]
If anyone has thoughts on how to create a functional dynamic action that defines which page the modal dialogues should cancel/submit to, let me know

**Comment by dededecline** [comment]
Closing issue, there is no good way to do this that I can find. Best avenue requires a dozen new pages, and even then not every button redirects properly.
