### ISSUE TITLE
good to have: theme roller

### ISSUE THREAD

**Issue by mpanoratra** [mpanoratra/cs347_final_project#15]

**Comment by brianquimio** [comment]
• Run Application
• Click “Theme Roller” from the menu bar at the bottom of the screen on the right
• Modify the colors – you can see the changes in real time
• Click “Save As” on the bottom right and save your style under “My Theme”
• Go to Application Builder
• Under Shared Components on the right side, under Theme, click “Universal Theme”
• Click on the “Styles” tab
• Click on “My Theme”
• Change “Is Current” from No to Yes
• Click Apply Changes
• Click on Apply Changes again.
• Run the Application, your theme should now be the default

**Comment by dededecline** [comment]
complete
