### ISSUE TITLE
good to have: apex timer plugin

### ISSUE THREAD

**Issue by mpanoratra** [mpanoratra/cs347_final_project#16]

**Comment by brianquimio** [comment]
Apex Timer Plugin:
• Go to http://www.oracle.com/technetwork/developer-tools/apex/application-express/apex-plug-ins-182042.html
• Download timer_v_1_0.zip
• In the application builder under shared components, under other components, click “plug-ins”
• Import dynamic_action_plugin_com_apex_times.sql
For each form:
• Create dynamic action. Name “timer_initialized”. Click next
• Event = “Page Load”. Selection Type = “Region”. Region = “Form on _____”. Click next
• Action = “Timer [Plug-in]” Expire in x Milliseconds = “60000”. Click next
• Selection Type = “Region”. Region = “Form on _____”. Click Create
• Create dynamic action. Name “hide_form”. Click next
• Event = “Timer Expired”. Selection Type = “Region”. Region = “Form on _____”. Click next
• Action = “Hide”. Uncheck Fire On Page Load. Click Next
• Selection Type = “Region”. Region = “Form on _____”. Click Create
• Create dynamic action. Name “alert”. Click next
• Event = Timer Expired”. Selection Type = “Region”. Region = “Form on _____”. Click next
• Action = “Alert”. Text = “Time has expired. Please load a new form”. Click next. Click create

Whenever the form loads, after 1 min the form should cancel and an alert will appear saying to load a new form.
